USE [master];
GO

CREATE DATABASE [$DbName$] ON PRIMARY 
    ( NAME = N'$DbName$', FILENAME = N'$DatabaseLocation$$DbName$.mdf', SIZE = 1024MB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024MB )
    LOG ON 
    ( NAME = N'$DbName$_log', FILENAME = N'$LogLocation$$DbName$_log.ldf', SIZE = 1024MB, MAXSIZE = UNLIMITED , FILEGROWTH = 1024MB );

ALTER DATABASE [$DbName$] SET COMPATIBILITY_LEVEL = 100;

IF ( 1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled') )
    BEGIN
        EXEC [$DbName$].[dbo].[sp_fulltext_database] @action = 'enable';
    END;

ALTER DATABASE [$DbName$] SET ANSI_NULL_DEFAULT ON; 
ALTER DATABASE [$DbName$] SET ANSI_NULLS ON; 
ALTER DATABASE [$DbName$] SET ANSI_PADDING ON; 
ALTER DATABASE [$DbName$] SET ANSI_WARNINGS ON; 
ALTER DATABASE [$DbName$] SET ARITHABORT ON; 
ALTER DATABASE [$DbName$] SET AUTO_CLOSE OFF; 
ALTER DATABASE [$DbName$] SET AUTO_CREATE_STATISTICS ON; 
ALTER DATABASE [$DbName$] SET AUTO_SHRINK OFF; 
ALTER DATABASE [$DbName$] SET AUTO_UPDATE_STATISTICS ON; 
ALTER DATABASE [$DbName$] SET CURSOR_CLOSE_ON_COMMIT OFF; 
ALTER DATABASE [$DbName$] SET CURSOR_DEFAULT  LOCAL; 
ALTER DATABASE [$DbName$] SET CONCAT_NULL_YIELDS_NULL ON; 
ALTER DATABASE [$DbName$] SET NUMERIC_ROUNDABORT OFF; 
ALTER DATABASE [$DbName$] SET QUOTED_IDENTIFIER ON; 
ALTER DATABASE [$DbName$] SET RECURSIVE_TRIGGERS OFF; 
ALTER DATABASE [$DbName$] SET  DISABLE_BROKER; 
ALTER DATABASE [$DbName$] SET AUTO_UPDATE_STATISTICS_ASYNC OFF; 
ALTER DATABASE [$DbName$] SET DATE_CORRELATION_OPTIMIZATION OFF; 
ALTER DATABASE [$DbName$] SET TRUSTWORTHY OFF; 
ALTER DATABASE [$DbName$] SET ALLOW_SNAPSHOT_ISOLATION OFF; 
ALTER DATABASE [$DbName$] SET PARAMETERIZATION SIMPLE; 
ALTER DATABASE [$DbName$] SET READ_COMMITTED_SNAPSHOT OFF; 
ALTER DATABASE [$DbName$] SET RECOVERY FULL; 
ALTER DATABASE [$DbName$] SET  MULTI_USER; 
ALTER DATABASE [$DbName$] SET PAGE_VERIFY NONE;  
ALTER DATABASE [$DbName$] SET DB_CHAINING OFF; 
ALTER DATABASE [$DbName$] SET READ_WRITE; 
ALTER DATABASE [$DbName$] SET HONOR_BROKER_PRIORITY OFF; 
